name: Laravel Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: '8.0'

      - name: Copy .env
        run: cp .env.example .env

      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --prefer-dist

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create SQLite Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Execute Tests (PHPUnit/Pest)
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test || echo "Tests failed" >> $GITHUB_ENV
        continue-on-error: true  # Continue even if tests fail

      - name: Notify on Failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.mailtrap.io
          server_port: 587
          username: ${{ secrets.MAILTRAP_USERNAME }}
          password: ${{ secrets.MAILTRAP_PASSWORD }}
          subject: 'Laravel Tests Failed'
          body: |
            The build has failed. Please check the logs for more details.
          to: tongsreng@itc.edu.kh
