name: Laravel CI

on:
  push:
    branches: [master]  
  pull_request:
    branches: [master]  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # Update PHP version to 8.1 or higher

      - name: Install dependencies
        run: |
          cp .env.example .env
          composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

      - name: Generate application key
        run: php artisan key:generate

      - name: Create SQLite database
        run: |
          mkdir -p database
          touch database/database.sqlite
          php artisan migrate --force --seed  # If migrations are needed

      - name: Run PHPUnit tests
        env:
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit

      - name: Notify on failure
        if: failure()
        run: echo "Tests failed" | mail -s "Laravel Tests Failed" enghav12@gmail.com
